In [1]:
# Run tomes on Nick's isolate genomes
import glob

In [2]:
gtdb_genomes = glob.glob('/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/*/*.fna')
gtdb_genomes[:5]

['/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/GCA_004000035.1/GCA_004000035.1_ASM400003v1_genomic.fna',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/GCA_024168675.1/GCA_024168675.1_ASM2416867v1_genomic.fna',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/GCA_030060415.1/GCA_030060415.1_ASM3006041v1_genomic.fna',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/GCA_030818145.1/GCA_030818145.1_ASM3081814v1_genomic.fna',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/ncbi_dataset/data/GCA_030946705.1/GCA_030946705.1_ASM3094670v1_genomic.fna']

In [16]:
import os
import subprocess
from IPython.display import display, clear_output

In [18]:
base = '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/gtdb_genomes/'
for i, infile in enumerate(gtdb_genomes):
    display(i)
    clear_output(wait=True)
    
    outfile_base = os.path.join(base, infile.split('/')[-2])
    command = f'cp {infile} {outfile_base}_genomic.fna'
    result = subprocess.run(command, shell=True, capture_output=True)
    command = f'prodigal -i {infile} -c -a {outfile_base}_proteins.faa -d {outfile_base}_proteins.fna -o {outfile_base}_proteins.gbk -p single'
    result = subprocess.run(command, shell=True, capture_output=True)

117

In [ ]:
    prodigal -i "${base}_filtered.fasta" -c \
             -a "${base}_proteins.faa" \
             -d "${base}_proteins.fna" \
             -o "${base}_prodigal_output.gbk" \
             -p meta

In [6]:
isolate_proteins = glob.glob('/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/*.faa')

In [7]:
isolate_proteins[:5]

['/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/8HZ65L_1_ASP410-2_proteins.faa',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/8HZ65L_3_24664_proteins.faa',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/barcode01_consensus_proteins.faa',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/barcode02_consensus_proteins.faa',
 '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/Arthrobacter/genomes/barcode03_consensus_proteins.faa']

In [36]:
with open('/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/tomes/even_genomes/even_genome_ids.txt', 'r') as handle:
    ids = [l.strip() for l in handle.readlines()]

In [37]:
from tqdm import tqdm

In [38]:
base = '/data/mhoffert/genomes/GTDB_r214.1/protein_faa_reps/bacteria/'
out_base = '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/tomes/even_genomes/'
for i in tqdm(ids):
    command = f'gunzip -c {base}{i}_protein.faa.gz > {out_base}{i}_protein.faa'
    result = subprocess.run(command, shell=True, capture_output=True)

100%|█████████████████████████████████████████| 997/997 [01:39<00:00, 10.01it/s]

In [61]:
import pandas as pd
import numpy as np

In [68]:
# load temperature data
temp_data = pd.read_csv('/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/metric_tables/20240327_metrics_df_full.tsv.gz', sep='\t', index_col=0)
temp_data.head()

genome2temp = temp_data.set_index('uid')[['temp']]
genome2temp['bin'] = pd.cut(genome2temp['temp'], np.linspace(10, 86, 16))
grouped = genome2temp.groupby('bin').apply(lambda x: x.sample(np.min([20, len(x)])))

/tmp/ipykernel_2970407/1643941622.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = genome2temp.groupby('bin').apply(lambda x: x.sample(np.min([20, len(x)])))

In [41]:
tomes_training_data = pd.read_csv('~/tools/Tome/tome/data/train.csv')

In [42]:
tomes_training_data.head()

,Organisms,AA,AC,AD,AE,AF,AG,AH,AI,AK,...,YN,YP,YQ,YR,YS,YT,YV,YW,YY,ogt
0,37_allobaculum_stercoricanis_bacteria,0.005367,0.001105,0.003809,0.003263,0.002990,0.004836,0.001432,0.006074,0.005794,...,0.001727,0.001648,0.001823,0.001773,0.002474,0.002147,0.002305,0.000403,0.001534,37
1,28_shewanella_algae_bacteria,0.010752,0.001212,0.005580,0.007041,0.003622,0.007179,0.001718,0.005544,0.005156,...,0.001011,0.001440,0.002096,0.002270,0.002069,0.001223,0.001472,0.000515,0.000947,28
2,37_bifidobacterium_saguini_bacteria,0.013873,0.001048,0.007266,0.006288,0.003457,0.008843,0.002224,0.005884,0.005065,...,0.000994,0.001298,0.001138,0.001713,0.001673,0.001711,0.002072,0.000453,0.000926,37
3,28_ochrobactrum_rhizosphaerae_bacteria,0.013460,0.000835,0.006199,0.006978,0.004413,0.009027,0.002097,0.007038,0.004678,...,0.000781,0.001143,0.000817,0.001730,0.001412,0.001173,0.001715,0.000378,0.000642,28
4,30_sphingomonas_haloaromaticamans_bacteria,0.022561,0.001093,0.008958,0.008309,0.004629,0.013291,0.002516,0.007588,0.003563,...,0.000569,0.001035,0.000689,0.002068,0.001160,0.000992,0.001508,0.000357,0.000635,30

In [49]:
import sys
sys.path.append('/data/mhoffert/tools/Tome/tome/core')
from core.predOGT import get_dimer_frequency

In [65]:
genome2temp

                    temp             bin
uid
GB_GCA_000376885.1  37.0  (35.333, 40.4]
GB_GCA_000016765.1  30.0  (25.2, 30.267]
GB_GCA_000242235.1  37.0  (35.333, 40.4]
GB_GCA_000283575.1  30.0  (25.2, 30.267]
GB_GCA_001054945.1  37.0  (35.333, 40.4]
...                  ...             ...
RS_GCF_905397275.1  30.0  (25.2, 30.267]
RS_GCF_907163105.1  30.0  (25.2, 30.267]
RS_GCF_905397435.1  27.0  (25.2, 30.267]
RS_GCF_910593845.1  30.0  (25.2, 30.267]
RS_GCF_907163265.1  30.0  (25.2, 30.267]

[8532 rows x 2 columns]

In [70]:
all_dimers = []
base = '/data/mhoffert/fiererlab/adenylate_kinase_ogt/data/validation_datasets/tomes/even_genomes/'
genomes = glob.glob(f'{base}*.fasta')
for g in tqdm(genomes):
    genome_id = g.split('/')[-1].replace('_protein.fasta', '')
    dimers = pd.Series(get_dimer_frequency(g, 5))
    dimers.loc['Organisms'] = genome_id
    dimers.loc['ogt'] = genome2temp.loc[genome_id, 'temp']
    all_dimers.append(dimers)
    # dimers[~dimers.index.str.contains('X')]

100%|█████████████████████████████████████████| 997/997 [17:34<00:00,  1.06s/it]

In [79]:
pd.concat(all_dimers, axis=1).T.reindex(columns=tomes_training_data.columns).to_csv('/data/mhoffert/tools/Tome/tome/data/train.csv', index=False)